### PR TITLE
test_ae9ap9.py: small deprication update with a py2/py3 issue (closes #179)

### LINKED ISSUE #179: ae9ap9 DeprecationWarning: Please use assertRaisesRegex instead (py3)
When testing ae9ap9 there is a Deprecation warning. 

```
tests/test_ae9ap9.py::ae9ap9Tests::test_setUnits_error
  /Users/balarsen/git/spacepy/tests/test_ae9ap9.py:41: DeprecationWarning: Please use assertRaisesRegex instead.
    self.assertRaisesRegexp(ValueError, '^(Units of FeV)', ans.setUnits, 'FeV')
```

Really minor fix but a py2 to py3 change.

### PR DESCRIPTION
**Pull request by balarsen**
test_ae9ap9.py: small deprication update with a py2/py3 issue around `unittest.TestCase.assertRaisesRegex` (Closes #179)

- [x ] Pull request has descriptive title
- [x ] Pull request gives overview of changes
- [x ] New code has inline comments where necessary
- [n/a ] Any new modules, functions or classes have docstrings consistent with SpacePy style
- [n/a ] Added an entry to CHANGELOG if fixing a major bug or providing a major new feature
- [ x] New features and bug fixes should have unit tests
- [ x] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)

This is a very minor change @drsteve even said in #179 how to fix this.

### CODE REVIEW

**Comment by balarsen** [comment]
Not sure why Travis failed, looks like in the numpy install part of the script. A kick may be in order (that I don't know how to do).

**Comment by jtniehof** [comment]
I'm not a fan of the monkey-punch, any reason we just can't call one vs. the other in the if/else?

**Comment by balarsen** [comment]
I don't care which way, the whole thing will go away when we drop py2. (#26) 

This way was @drsteve 's recommendation.

**Comment by jtniehof** [comment]
I think I've identified what gives me the willies. The getattr is unnecessary since can just do a "dot". And it's assigning on the unbound method of the class and then hoping that the bound method of the instance will get the picture. I'm guessing it works or we wouldn't be having this conversation, and it also should go completely away in six months or so, but I'd be more comfortable with:
```
if hasattr(self, 'assertRaisesRegex'):
    self.assertRaisesRegex(ValueError, '^(Units of FeV)', ans.setUnits, 'FeV')
else: #Py2k
    self.assertRaisesRegexp(ValueError, '^(Units of FeV)', ans.setUnits, 'FeV')

```
Or:
```
if not hasattr(self, 'assertRaisesRegex'): # Py2k
    self.assertRaisesRegex = self.assertRaisesRegexp
self.assertRaisesRegex(ValueError, '^(Units of FeV)', ans.setUnits, 'FeV')

```

I can open up another PR or force-push to this if it's better to have my fingerprints on it that way. (I could try suggesting a change but don't know if that gives us another commit, do we want to try it and learn?). I know this is getting a bit bikesheddy.

**Comment by balarsen** [comment]
@jtniehof , supposedly I was able to push a new update using your 1st suggestion above. Have a poke, should be done.

**Comment by jtniehof** [comment]
That's a bit of a mess because it includes a merge commit. Is it possible to force-push something with just your change?

**Comment by balarsen** [comment]
"force-push something" I do not understand this concept...

**Comment by jtniehof** [comment]
Force-pushing to a PR overwrites your previous commit history on that PR rather than adding to it. In this case you introduced a merge from master rather than rebasing your history on new master, and that's going to munge history for a long time.

What will probably do it is:

- checkout your branch
- git rebase --interactive origin/master
- remove the merge commit altogether
- push to this branch with `--force`

But this is a lot of farting around for a two-line change. You can just throw away your local branch and create a new one with just that change and then still force-push to that branch.

**Comment by jtniehof** [comment]
Actually I think I can probably unpickle this and then I'll send you email with what I did. It'll be a bit later.

**Comment by jtniehof** [comment]
Since I've got my fingerprints on this for the rebase force-push, I'm comfortable doing the rebase-and-merge once the checks complete, if you're good with it.

**Comment by balarsen** [comment]
I’m good with it. Your email of notes was how you did it?

**Comment by jtniehof** [comment]
Yep, that was how I unpickled it. Both easier and harder than I expected, in some ways....

**Pull request merged**
