### PR TITLE
Use oldest-supported-numpy in build reqs

### PR DESCRIPTION
**Pull request by dstansby**
Fixes https://github.com/spacepy/spacepy/issues/679. As described at https://github.com/scipy/oldest-supported-numpy, this should avoid the numpy versions having to be continually updated in the requirements, and will keep them up to date.

- [ ] Pull request has descriptive title
- [ ] Pull request gives overview of changes
- [ ] New code has inline comments where necessary
- [ ] Any new modules, functions or classes have docstrings consistent with SpacePy style
- [ ] Added an entry to release notes if fixing a significant bug or providing a new feature
- [ ] New features and bug fixes should have unit tests
- [ ] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)

### CODE REVIEW

**Comment by jtniehof** [comment]
I looked into oldest-supported-numpy for #639 and #649 since, indeed, doing this by hand is not much fun. Unfortunately I seem to have lost most of my notes on why it didn't work out. I remember part of the issue is that it's set to require the oldest numpy _with a binary wheel_ and that broke things on some older numpy, including those that had binaries in conda. It also doesn't distinguish between Apple Silicon and other ARM so it broke Raspberry Pi support.

It doesn't seem like there's any way to avoid having to disable build isolation in some circumstances, it's just a question of which circumstances.

**Comment by jtniehof** [comment]
I had a shower moment (actually cooking breakfast, but still) and realized that we can probably use no-build-isolation while making the binary wheels (where full control is the most important) and then use oldest-supported-numpy for the rest. I'm not sure of the set of people who won't be using binary wheels (once I have the Mac binaries) but also get thrown by no-build-isolation, but that might be the right solution. I will have to double-check just how bad the situation is on Pi.

**Comment by dstansby** [comment]
Going to close this since it doesn't seem like it's going to be merged.

**Comment by jtniehof** [comment]
I was actually just looking back at this in the context of some challenges in #723 (and was leaving it open until I was done with that work). For now there are enough moving pieces that it's still working out best to do the versioning by hand, but I'm going to keep oldest-supported-numpy in my back pocket--e.g. it might appear as a backstop for unreleased Python versions.

This discussion's been useful; thanks.

**Pull request closed without merging**
