### PR TITLE
Rename plot spectrogram class to Spectrogram

### PR DESCRIPTION
**Pull request by jtniehof**
This PR renames `plot.spectrogram.spectrogram` to `plot.spectrogram.Spectrogram` to start unraveling the name clash between class and module (#358). For now, it reintroduces the old name in the `plot` namespace to support old code, but issues a `DeprecationWarning` so we can remove it later.

Note this does mean the documentation build still has warnings and weirdness because of the clash; I did verify that things build better before reintroducing the old name.

## PR Checklist

- [X] Pull request has descriptive title
- [X] Pull request gives overview of changes
- [X] New code has inline comments where necessary
- [X] Any new modules, functions or classes have docstrings consistent with SpacePy style
- [X] Added an entry to CHANGELOG if fixing a major bug or providing a major new feature
- [X] New features and bug fixes should have unit tests
- [X] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)

### CODE REVIEW

**Review by balarsen — COMMENTED** [review]
This all looks good, let me pull it and bash on it with `grep` then will approve. These refactors are sneaky.

**Comment by balarsen** [comment]
Here is as good as anywhere to make notes on places where the refactor may have missed. 

Some in the code:
1. `plot/spectrogram.py:20::class:`spectrogram` to rebin the data for visualization.`
2. `plot/__init__.py:90:from .spectrogram import *`     should this one be caps?

Some in the generated docs
1. `Doc/build/html/autosummary/spacepy.plot.colourmaps.html:23:    <link rel="next" title="spacepy.plot.spectrogram" href="spacepy.plot.spectrogram.html" />`
2. `Doc/build/html/autosummary/spacepy.plot.colourmaps.html:41:          <a href="spacepy.plot.spectrogram.html" title="spacepy.plot.spectrogram"`
3. `Doc/build/html/autosummary/spacepy.plot.colourmaps.html:66:                        title="next chapter">spacepy.plot.spectrogram</a></p>`
4. `Doc/build/html/autosummary/spacepy.plot.spectrogram.html:8:    <title>spacepy.plot.spectrogram &#8212; SpacePy v0.2.2 Manual (DRAFT)</title>`

**Comment by jtniehof** [comment]
> Here is as good as anywhere to make notes on places where the refactor may have missed.

I'll look these over and update the PR.

>     1. `plot/spectrogram.py:20::class:`spectrogram` to rebin the data for visualization.`

Yeah, I noticed that one about two seconds after submitting. I think it's the only one that actually needs a change.

>     2. `plot/__init__.py:90:from .spectrogram import *`     should this one be caps?

Nope, that's importing everything from the `spectrogram` module, which will stay lowercase.

> Some in the generated docs

Definitely do a `make clean` in the docs before building them to be sure.

>     1. `Doc/build/html/autosummary/spacepy.plot.colourmaps.html:23:    <link rel="next" title="spacepy.plot.spectrogram" href="spacepy.plot.spectrogram.html" />`

That's perfectly fine, there will still be a `spacepy.plot.spectrogram.html` and it's just from the previous/next. It'll ultimately be the module docs once this is all done.

>     2. `Doc/build/html/autosummary/spacepy.plot.colourmaps.html:41:          <a href="spacepy.plot.spectrogram.html" title="spacepy.plot.spectrogram"`
Same thing, really

>     3. `Doc/build/html/autosummary/spacepy.plot.colourmaps.html:66:                        title="next chapter">spacepy.plot.spectrogram</a></p>`

Also same.

>     4. `Doc/build/html/autosummary/spacepy.plot.spectrogram.html:8:    <title>spacepy.plot.spectrogram &#8212; SpacePy v0.2.2 Manual (DRAFT)</title>`

Again, we're still going to have this page exist.

**Comment by jtniehof** [comment]
Fixed that missed cap-update, that should be it now.

**Review by balarsen — APPROVED** [review]
Looks good to me.

**Pull request merged**
