### PR TITLE
Update to toolbox.normalize(), arbitrary range

### PR DESCRIPTION
**Pull request by balarsen**
I needed the ability to normalize to an arbitrary range and some thinking and research led to an elegant solution using numpy.interp. 

This is useful for 0-255 scaling, -1-1, or whatever a user may want. Tests updated and all pass.

### CODE REVIEW

**Comment by balarsen** [comment]
Ugg, how did this other commit get in here?  Ugg. Anyone know how to drop it.

**Comment by jtniehof** [comment]
You committed it to (your) master. PR are tied to a branch, not a commit.

**Comment by balarsen** [comment]
Any thoughts on how to roll that back? Or save off the changes and start
over?

**Comment by jtniehof** [comment]
Do a git rebase --interactive, remove this commit, and force-push to your master.

**Comment by balarsen** [comment]
Killing this in favor of #78

**Pull request closed without merging**
