### PR TITLE
time: minor update in _days1958totai(), Closes #462

### LINKED ISSUE #462: time: DeprecationWarning: Converting `np.integer` or `np.signedinteger` to a dtype is deprecated.
Test tests for `time` raise a few `DeprecationWarning` instances. 

### Minimal example to reproduce issue:
```
 python test_time.py -v TimeClassTests.testDataPersistsRDT
```
also
```
python test_time.py -v TimeFunctionTests.test_days1958toTAI
```

### Error message/Traceback:
```
testDataPersistsRDT (__main__.TimeClassTests)
Verify input data is returned for RDT input ... /home/balarsen/miniconda3/envs/python3/lib/python3.8/site-packages/numpy/core/_asarray.py:136: DeprecationWarning: Converting `np.integer` or `np.signedinteger` to a dtype is deprecated. The current result is `np.dtype(np.int_)` which is not strictly correct. Note that the result depends on the system. To ensure stable results use may want to use `np.int64` or `np.int32`.
  return array(a, dtype, copy=False, order=order, subok=True)
```

```
test_days1958toTAI (__main__.TimeFunctionTests)
Test fractional days since 1958 to TAI ... /home/balarsen/miniconda3/envs/python3/lib/python3.8/site-packages/numpy/core/_asarray.py:136: DeprecationWarning: Converting `np.integer` or `np.signedinteger` to a dtype is deprecated. The current result is `np.dtype(np.int_)` which is not strictly correct. Note that the result depends on the system. To ensure stable results use may want to use `np.int64` or `np.int32`.
  return array(a, dtype, copy=False, order=order, subok=True)
```

### OS, Python version, and dependency version information:
```
Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.10
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
numpy=1.19.4
scipy=1.5.4
matplotlib=3.3.3
```

### Version of SpacePy
376539978a44189faf433695ae169f102edac9b2

### PR DESCRIPTION
**Pull request by balarsen**
Really minor update to _days1958totai() to Close #462 , I greped around and `np.integer` and `np.float` to not appear anywhere else in the code base. 

- [X] Pull request has descriptive title
- [X] Pull request gives overview of changes
- [X] New code has inline comments where necessary
- [X] Any new modules, functions or classes have docstrings consistent with SpacePy style
- [X] Added an entry to CHANGELOG if fixing a major bug or providing a major new feature
- [X] New features and bug fixes should have unit tests
- [X] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)

I cannot think of a good way to add a unittest for this. I'm all ears if anyone has ideas.

### CODE REVIEW

**Comment by jtniehof** [comment]
See discussion in #462.

**Comment by jtniehof** [comment]
1. Can you rebase this to a single commit once we've got agreement on the proper type?
2. In the past we haven't put fixes for numpy deprecation warnings in the CHANGELOG. It's really too minor.

**Comment by balarsen** [comment]
>     1. Can you rebase this to a single commit once we've got agreement on the proper type?

Yes, I will have to google how but will. 
 
>     2. In the past we haven't put fixes for numpy deprecation warnings in the CHANGELOG. It's really too minor.

Sure, I debated and erred on the side of verbosity. I will remove.

**Comment by jtniehof** [comment]
You'll want a `rebase --interactive` with squash, e.g. https://sethrobertson.github.io/GitFixUm/fixup.html and https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history

Will have to force-push the resulting commit to the PR branch.

**Comment by jtniehof** [comment]
Looks like you figured that out :) Can do a simple `commit --amend` to fix the typo in the commit message ;)

**Comment by balarsen** [comment]
Changed were so minor I just nuked from orbit and redid them. `git reset --hard ...`

**Comment by balarsen** [comment]
Done, and *this all* is why one works in your own branch!

**Comment by balarsen** [comment]
@jtniehof , this is done. No rush but fell off the table with the release.

**Comment by jtniehof** [comment]
It's possible to do a unit test to capture warnings, call the function, and then make sure there are no warnings...but hardly worth it.

**Review by jtniehof — APPROVED** [review]

**Comment by jtniehof** [comment]
For the sake of completeness I'm going to run the whole developer-side unit test script, and will merge when it's done.

**Comment by jtniehof** [comment]
Tests are happy.

**Pull request merged**
