### PR TITLE
Issue178, work on not closed yet, omni thoughts needed

### PR DESCRIPTION
**Pull request by balarsen**
This is work toward #178. Cannot close yest but this and the other pulls fix all but omni.

### CODE REVIEW

**Comment by balarsen** [comment]
OK, not sure how to fix this...

**Comment by jtniehof** [comment]
I'm okay with having this merged and coming back to omni later. Brian, can you work through the conflict rebase?

**Comment by jtniehof** [comment]
Poke @balarsen . Do you want me to handle the conflict rebase?

**Comment by balarsen** [comment]
If you can that would be awesome. I have been on travel and not fully sure
how.

Brian

**Comment by jtniehof** [comment]
The problem was you conflicted with yourself :) You made changes on master that almost reproduced changes on this issue. Conflict resolved and I force-pushed the rebase. Running tests locally before merging though.

**Comment by jtniehof** [comment]
This is a big enough change and a big enough improvement that I'm merging and we can handle omni later.

**Pull request merged**
