### PR TITLE
Skip Q-D daily files for years in ViRBO file (Closes #373)

### LINKED ISSUE #373: Don't grab daily Q-D files for times that are in the "big" file
#338 grabs an omnibus Qin-Denton file from the old ViRBO source and then grabs dailies from NMC to fill out into the future. The overlap is actually pretty big, so it would be better to examine the big single file and figure out where it ends before crawling the NMC files.

### PR DESCRIPTION
**Pull request by jtniehof**
This PR changes toolbox.update to check for the last year in the ViRBO omnibus file, and only starts downloading daily files from NMC from that year. There's still some overlap, but a whole lot less (and this is easier than trying to get things down to the day.)

- [X] Pull request has descriptive title
- [X] Pull request gives overview of changes
- [X] New code has inline comments where necessary
- [X] (N/A) Any new modules, functions or classes have docstrings consistent with SpacePy style
- [X] Added an entry to CHANGELOG if fixing a major bug or providing a major new feature
- [ ] New features and bug fixes should have unit tests
- [X] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)

 (EDIT: Closes #373 . Does it not pick it up from the title?)

### CODE REVIEW

**Comment by drsteve** [comment]
Waiting on tests again, because I had to hit the "update branch" button to allow the merge. I'll come back to the PR later tonight.

**Comment by jtniehof** [comment]
That should be a rebase not a merge. I'll take a look in the morning. Well,
later in the morning.

**Comment by jtniehof** [comment]
Okay, the issue was the branch protection...I was requiring up-to-date, which in order to allow for a rebase workflow, would require people to force-push the branch immediately before merge. So I removed that rule. I also removed the rule for signed commits, since apparently that's not just the normal git SHA. And it looks like someone (probably @drsteve ) already narrowed the status check requirement to the pull request build, which seems to keep up to date, rather than the branch build, which occasionally doesn't realize it's finished.

So I think that's all tweaked appropriately and ready for merge, and I like still sticking with having someone other than author of the PR do the merge (even with an approving review.)

**Comment by jtniehof** [comment]
I added one more protection rule to block merge commits and enforce the rebase workflow.

**Pull request merged**
