### PR TITLE
New function to rebin array by another array

### PR DESCRIPTION
**Pull request by jtniehof**
This PR adds a function that allows the rebinning of one dimension of an array by data in another array. The canonical example of this is going from an array organized by sensor number and tagged by pitch angle, to one binned by pitch angle.

This is the type of thing I've found myself doing a _lot_ and nailing it down in general is actually nontrivial.

I think the one thing lacking in the documentation is a full end-to-end example, but since this usually involves big arrays it's hard to come up with a concise example.

- [X] Pull request has descriptive title
- [X] Pull request gives overview of changes
- [X] New code has inline comments where necessary
- [X] Any new modules, functions or classes have docstrings consistent with SpacePy style
- [X] Added an entry to CHANGELOG if fixing a major bug or providing a major new feature
- [X] New features and bug fixes should have unit tests
- [X] (N/A) Relevant issues are linked to (e.g. `See issue #` or `Closes #`)

### CODE REVIEW

**Comment by jtniehof** [comment]
If you look at the code, you'll note I use `numpy.digitize`. It's only the first step in a process.

**Comment by balarsen** [comment]
Ok, fair enough. 

I do this all the time but using pandas. 
```

cuts = pd.cut(data, [1,4,7,10])
df.groupby(df['data'].loc[cuts]).mean(). # or .std()
```

**Comment by jtniehof** [comment]
Dataframes aren't N-D, last I checked. It says "Two-dimensional" at the top of the documentation.

If you can tell me how in Pandas I can take an array of flux that's dimensioned Nt times by Nl look directions by Ne energies and convert it to Nt times by Np pitch angles by Ne energies via an array of pitch angles dimensioned Nt by Np by Ne, I'm all ears.

This is not rebinning in the sense of scaling up or down.

**Comment by balarsen** [comment]
that package is called `xarray` does all that. I find it a PITA but it does do all that. At one point I made HOPE spectrograms from it using only xarray built ins.

**Comment by jtniehof** [comment]
I'll see what I can do. As I said, it's hard to come up with an example that's self-contained and works but it's clear from this discussion the purpose isn't apparent. And then you can either tell me how to do it in xarray or note that it can't be done.

**Comment by balarsen** [comment]
> I'll see what I can do. As I said, it's hard to come up with an example that's self-contained and works but it's clear from this discussion the purpose isn't apparent. And then you can either tell me how to do it in xarray or note that it can't be done.

Sounds good. I am not really saying that xarray should be a dependency (maybe a bit too obscure unless we need to do a lot of this stuff) but overall the conversation is good to have.

**Comment by balarsen** [comment]
>     This is clearest with an example. Consider a flux as a function of time,
>     energy, and the look direction of a detector (could be multiple detectors,
>     or spin sectors.) The flux is then 3-D, dimensioned Nt x Ne x Nl. Now
>     consider that each look direction has an associated pitch angle that is
>     a function of time and thus stored in an array Nt x Nl. Then this function
>     will redimension the flux into pitch angle bins (rather than tags.)

One place would be what are the output expect dimensions of the above? Maybe adding in concrete numbers like assume there are 3400 times, 16, sectors, and 3 detectors.

**Comment by jtniehof** [comment]
Read the paragraph after your quote and it'll give you the output dimensions.

The short is: this takes one dimension of an array and replaces it with a different dimension that can be determined from the first.

**Comment by jtniehof** [comment]
I've pushed a pretty extensive example in the docstring. You're definitely going to need to pull, install, and build the docs to follow it.

**Comment by jtniehof** [comment]
The build passed; there's something screwed up with Travis where it's not reporting out as successful. Since they're actually the same build I can't restart it. Travis also seems to keep logging me out every time I blink, so I think it's messed up.

**Comment by balarsen** [comment]
That is an awesome example! Let me study it a bit more.

**Comment by balarsen** [comment]
@jtniehof , thanks for this great example. I am happy with this. Let me know what you are thinking with the travis #357 , can merge this when you are happy.

**Comment by jtniehof** [comment]
This should be independent of #357 ...I got to playing with that because of the double-check thing here, but they're actually unrelated.

**Comment by jtniehof** [comment]
So good to merge when you are.

**Comment by jtniehof** [comment]
Incidentally, I did find what happens with the double-checks...apparently there's one for the PR itself and one for the branch underlying it, they do go to a single build but sometimes it isn't properly reported out on both.

**Comment by jtniehof** [comment]
Actually, maybe hold off a bit...I want to look if I can use plot.spectrogram.simpleSpectrogram to make the example a little shorter (and more SpacePy-y).

**Comment by jtniehof** [comment]
This is _much_ nicer with `simpleSpectrogram`. The latest push, in addition to switching the example, makes two simpleSpectrogram changes:

1. It fixes the case where Y is already bin edges instead of bin centers. For X this was checked, but Y was assumed to be bin centers.
2. It fixes the case where no colorbar label is specified. This was being passed None which got cast to a string, 'None', labeling the colorbar with "None" which looks weird.

Sorry for mixing the stuff together but it didn't seem worth opening a PR just for those, particularly since this one depends on the first fix.

**Comment by jtniehof** [comment]
Ready to merge once the checks pass (but do take a look at those fixes.)

**Comment by jtniehof** [comment]
Poke for the merge, unless @drsteve wants to take a look at the simpleSpectrogram changes.

**Comment by drsteve** [comment]
I can take a look tomorrow...

**Pull request merged**
