### PR TITLE
Issue 116

### LINKED ISSUE #116: threading update in python 3.7.3 leads to isAlive() is deprecated
In python 3.7.3 the test in test_toolbox.py throw a PendingDeprecationWarning. 

spacepy/toolbox/__init__.py:2502: PendingDeprecationWarning: isAlive() is deprecated, use `is_alive()` instead   `if t.isAlive()`:

The code snippit is:
```
    t = ReturningThread(None, target, None, args, kwargs)
    t.start()
    retval = t.join(timeout)
    if t.isAlive():
        raise TimeoutError()
    return retval
```
Which maybe should just be:
```
    t = ReturningThread(None, target, None, args, kwargs)
    t.start()
    retval = t.join(timeout)
    if t.is_alive():
        raise TimeoutError()
    return retval
```

I am not sure on the backwards compatibility and all the threading is complex enough I won't update this myself. 

Darwin-18.5.0-x86_64-i386-64bit
sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
numpy=1.16.2
scipy=1.2.1
matplotlib=3.0.3

### PR DESCRIPTION
**Pull request by balarsen**
Minor change to close #116, at least python 2.7 has the desired function in there already. Do we stiull support 2.6?

### CODE REVIEW

**Comment by drsteve** [comment]
Question: Can you take a look at why you have a bunch of old commits and merge commits in here?
My suggested fix would be to close this PR, make sure your local master is up to date, then make a new branch for this commit from master. Then you can check out that new branch and cherrypick the last commit here. That should give us a clean PR to work with.
Thanks!

**Comment by balarsen** [comment]
I think I did exactly this... " My suggested fix would be to close this PR,
make sure your local master is up to date, then make a new branch for this
commit from master. Then you can check out that new branch and cherrypick
the last commit here. That should give us a clean PR to work with."

I will take a look, funny it only lists one changed file but 12 commits...
WTH

**Comment by drsteve** [comment]
It's definitely weird... there are duplicated *old* commits \(that have already been merged in a previous PR\), plus a bunch of merge commits.

Just to answer your question about support for 2.6:
- We don't test on 2.6, and our README explicitly says we support 2.7 and 3.x

So yeah, we're not explicitly supporting 2.6 any more.

**Comment by balarsen** [comment]
Going to close and try for a clean one without all the extra stuff.

**Pull request closed without merging**
