### PR TITLE
Fixes for datamanager under Windows

### PR DESCRIPTION
**Pull request by jtniehof**
Basically just expiicitly uses POSIX paths (as is the design for RePath), although adds an option for native paths in some low-level utility functions where it might be handy.

### CODE REVIEW

**Comment by drsteve** [comment]
`test_datamanager.py` doesn't pass on my system (Win 10, Python 3.7.1, 32-bit) with this PR.
It doesn't hang, so that's good... and it's failing less than it was before the PR, so also good.

```
morle@LAPTOP-L07QR9PQ MINGW64 ~/OneDrive/Documents/GitHub/spacepy/tests (upstrPR98)
$ python test_datamanager.py
This unreleased version of SpacePy is not supported by the SpacePy team.
F...C:\Users\morle\Anaconda3\envs\spacepy\lib\site-packages\spacepy\datamanager.py:405: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if numpy.shape(fillval) != fillshape:
...........
======================================================================
FAIL: test_files_matching (__main__.DataManagerClassTests)
Files matching a format
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_datamanager.py", line 66, in test_files_matching
    numpy.testing.assert_array_equal(expected, output, 'Case:' + str(c))
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\site-packages\numpy\testing\_private\utils.py", line 865, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "C:\Users\morle\Anaconda3\envs\spacepy\lib\site-packages\numpy\testing\_private\utils.py", line 789, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal
Case:{'files1': ['rbspa_ect-hope-sci-L2_20150409_v4.0.0.cdf', 'rbspa_ect-hope-sci-L2_20150410_v4.0.0.cdf'], 'files2': ['rbspa_ect-hope-sci-L2_20150409_v4.1.0.cdf'], 'regex': 'rbspa_ect-hope-sci-L2_%Y%m%d_v(\\d\\.){3}cdf', 'dt': None, 'descend': False}
(mismatch 100.0%)
 x: array(['data/datamanager_test/1\\rbspa_ect-hope-sci-L2_20150409_v4.0.0.cdf',
       'data/datamanager_test/1\\rbspa_ect-hope-sci-L2_20150410_v4.0.0.cdf',
       'data/datamanager_test/2\\rbspa_ect-hope-sci-L2_20150409_v4.1.0.cdf'],
      dtype='<U65')
 y: array(['data\\datamanager_test\\1\\rbspa_ect-hope-sci-L2_20150409_v4.0.0.cdf',
       'data\\datamanager_test\\1\\rbspa_ect-hope-sci-L2_20150410_v4.0.0.cdf',
       'data\\datamanager_test\\2\\rbspa_ect-hope-sci-L2_20150409_v4.1.0.cdf'],
      dtype='<U65')

----------------------------------------------------------------------
Ran 15 tests in 0.187s

FAILED (failures=1)
```

**Comment by jtniehof** [comment]
That failure is unrelated to these changes and is fixed in #97.

**Comment by drsteve** [comment]
Sure?

This looks like a failure due to path separators, not sort order.
Also, I just fetched PR #97 into a local branch with this PR and I still get the same test failure.

**Comment by jtniehof** [comment]
No, not sure, thanks :) I'll take a look.

**Comment by jtniehof** [comment]
Updated; try that. With bonus DeprecationWarning removal. Ugh.

**Comment by drsteve** [comment]
👍

**Pull request merged**
