### PR TITLE
Reimplement dmarray and add continuous integration

### PR DESCRIPTION
**Pull request by drsteve**
Major changes:
- Added .travis.yml file to set up Travis CI and build/run test suite
- Reimplemented dmarray so it's a subclass of numpy.ma.MaskedArray, not of numpy.ndarray
- pycdf update to not compare or slice iterators in testing and check_well_formed method
- Updated included leapsecond file
- fix to test_time.py: test_randomDate regression test as expected result differs between 2.7 and 3.6

dmarray modifications fix issue #12  

[Test results for my branch](https://travis-ci.com/drsteve/spacepy)
Only 3.5 and 3.6 are currently tested here as the 2.7 build was freezing (on Travis) on compiling C sources. All tests on 2.7 pass on my local machine.

### CODE REVIEW

**Comment by drsteve** [comment]
I'll leave this for review, but I just hit something that might want modifying...
When I was borrowing from the MaskedArray I was using up-to-date code as a raference. So the __repr__ in dmarray uses numpy.core.arrayprint.dtype_is_implied, which wasn't implemented until numpy 1.14. That puts a pretty hard version dependency on the new dmarray unless I rewrite the __repr__.

**Comment by jtniehof** [comment]
Sorry to leave this hanging; I need to look over the pycdf stuff and double-check it. check_well_formed is scuzzy both because it's fairly early code and because it's just a wicked complicated problem. And I think flat may have changed; I remember encountering the "wait it's an iterator now" thing a couple of years ago. Either it used to be, or I thought it was, a view.

**Comment by jtniehof** [comment]
There's something weird with this PR now. Since you've been updating your master as things are merged onto the mainline master, we now have some commits on both side (e.g. "benchmark: add pycdf entry typing.") While the PR is waiting, you need to rebase your master against spacepy/master. Incorporating this is going to be "fun."

**Comment by jtniehof** [comment]
I'm also not thrilled about "from distutils.version import LooseVersion as Version". Losing the namespacing is bad enough although I know it's common in the codebase and I've probably lost that war. Also renaming it make the readability really bad.

**Comment by jtniehof** [comment]
Okay, I think this is how we have to handle it:
1) Rebase your master to 144901c115b9cae95585db4df8c455675b4ac003 (i.e. throw away c3fa81368e9c6d441a139dbd57bb3a83859c5472) and force push. That will update this PR to not have the duplicated commit.
2) I'm going to then submit a PR against YOUR master with a few changes. Once you accept that on your branch, this will be updated.
3) Then I'll accept this.

**Comment by jtniehof** [comment]
What was wrong with flat[0], incidentally? https://stackoverflow.com/a/36392089/336412 and https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.ndarray.flat.html#numpy.ndarray.flat show that it can be sliced. Was this causing a problem?

**Comment by jtniehof** [comment]
Okay, I see that switching to a masked array base changes the behavior of flat, so that it returns a different object that doesn't behave like the flat iterator. That's annoying and would potentially affect any other code that treats dmarrays like ndarrays in this way.

**Comment by jtniehof** [comment]
>>> q = numpy.ma.array([1, 2, 3])
    >>> q.flat[0]
    1
    >>> z = numpy.ma.array([datetime.datetime(2010, 1, 1), datetime.datetime(2010, 1, 2)])
    >>> z.flat[0]
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/dist-packages/numpy/ma/core.py", line 2589, in __getitem__
        result = self.dataiter.__getitem__(indx).view(type(self.ma))
    AttributeError: 'datetime.datetime' object has no attribute 'view'
    >>> foo = numpy.array([datetime.datetime(2010, 1, 1), datetime.datetime(2010, 1, 2)])
    >>> foo.flat[0]
    datetime.datetime(2010, 1, 1, 0, 0)

That's not high on my fun list. I know we had definite breakage with dmarray subclassing ndarray but it looks like we're going to be chasing MaskedArray bugs now. I also wonder if our issues with converting dmarray to MaskedArray wouldn't be better solved by trying to fix MaskedArray, now that we're into having to fix MaskedArray bugs.

**Comment by drsteve** [comment]
The different behavior in slicing flat iterators is indeed the issue I was seeing, and hence the changes to check_well_formed and a couple of tests. My feeling is that yes, it leaves us with some incompatibilities between ndarray and dmarray... but the incompatibilities are now buried much deeper and are an upstream bug. The problems we have with the old dmarray not masking well are much greater in magnitude, are far more visible, and then the problem is firmly ours. Maybe the ultimate fix is to work out a slick way of wrapping an ndarray such that it *quacks* like an ndarray, but I think that's a lot of work relative to the change to inheriting from MaskedArray. 

I would like to point out that the numpy datetime64 support doesn't have the "view" issue:
`  y = numpy.ma.array([datetime.datetime(2010, 1, 1), datetime.datetime(2010, 1, 2)]).astype(numpy.datetime64)`
`y.flat[0]`
`numpy.datetime64('2010-01-01')`



So what to do?

The rebase and merge should bring this in, even with the additional commit I made while this PR was open. I may be wrong, but I don't think it would require cleanup. So we can do one of several things - let me know which you want:
1. Hit the "rebase and merge" button
2. Rebase my fork as you recommended, merge a new PR into my fork (with what changes?), then come back to this PR and rebase/merge
3. Something else, details needed.

Feel free to hit me up offline to talk me through your preferred option.

**Comment by drsteve** [comment]
Okay, MaskedArray might be a non-starter...
My guess is that we should probably push this as a bug report upstream...

In [1]: import numpy as np
In [2]: import datetime as dt
In [3]: a = np.ma.MaskedArray([dt.datetime.now()])
In [4]: a.any()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-237d43746c7e> in <module>()
----> 1 a.any()

/home/smorley/.local/lib/python2.7/site-packages/numpy/ma/core.pyc in any(self, axis, out, keepdims)
   4792         mask = _check_mask_axis(self._mask, axis, **kwargs)
   4793         if out is None:
-> 4794             d = self.filled(False).any(axis=axis, **kwargs).view(type(self))
   4795             if d.ndim:
   4796                 d.__setmask__(mask)

AttributeError: 'datetime.datetime' object has no attribute 'view'


Of course, the MaskedArray-derived dmarray suffers the same problem. This is a killer for me in its current state.

**Comment by jtniehof** [comment]
The encouraging thing is, I think that's the same place where flat subscripting fails, some sort of bug on touching the masks with object arrays. So we might be able to fix it upstreams and if we're very lucky we can monkey-patch it in to dmarray.

We really do want your CI stuff. I wonder about accepting this PR, then putting together another commit that reverts dmarray back to ndarray for now, and re-opening a branch off of master that reverts the reversion and lets us work on it for awhile. Thoughts?

**Comment by drsteve** [comment]
That seems messy. How about I deal with the mess at my end?
I think I can probably make two new branches, one with the CI and one with the dmarray updates. Then I can send a new PR for the CI stuff (to master) and I'll work out how to send a PR for the dmarray stuff to a new_dmarray branch. Hopefully I'll get to that tomorrow and once that's all done we can just close this PR?

I know that separates the discussion from the dmarray PR, but really the core of the discussion isn't about *our* problem so much as it is about a numpy.ma.MaskedArray problem.

**Pull request closed without merging**
