### PR TITLE
Convert CI to GitHub actions

### LINKED ISSUE #455: Migrate CI off Travis
Travis migrated to a [new billing structure](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) back in November. As part of this change, we were put onto a plan with a fixed number of credits, nonrefilling. Those credits have now been used and our builds are not executing. A later post [claims commitment to Open Source](https://blog.travis-ci.com/oss-announcement) but with no further information. The original post states that open source projects will have to request credits on a case-by-case basis. [It appears those are no longer being considered](https://twitter.com/james_hilliard/status/1336081776691843072). Even before that, [reports are that requirements include nobody on the project getting paid](https://news.ycombinator.com/item?id=25338983).

I have disabled the requirement that CI pass to merge PRs; reviewers should build and run the unit tests (there's a developer/scripts/test_all.sh that can help with this on Linux). I have also suspended access by the Travis GitHub app.

Options that I see:

1. Pay for Travis. Cheapest plan I found was $70/mo.
2. Request Open Source credits, with the understanding we'll probably have to keep requesting them.
3. Stop using cloud-hosted and GitHub-integrated CI in favor of hand-run tests, e.g. by PR reviewers. Our CI doesn't get us Mac or Windows anyhow (Travis charges more for Mac now) so maybe a duct tape solution is the way.
4. Migrate to CircleCI. We're using it on dbprocessing and it's okay, although two months ago we went through a similar dance with DockerHub changing the terms of free access, which fortunately worked out okay.
5. Migrate to Jenkins, either self-hosted or finding a provider. Frankly option 3 might be easier.
6. Migrate to [GitHub Actions](https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works).

My recommendation would be to try GitHub Actions with maybe a side of punching up our developer-hosted testing. This can allow for much more comprehensive testing and deal with cross-platform as well. And it puts us in a better position in case something similar happens with whatever CI we're using. If GitHub becomes intractable we're in trouble anyhow.

### PR DESCRIPTION
**Pull request by jtniehof**
This PR switches our CI from Travis to GitHub Actions. Closes #455 .

Also includes documentation on how the CI is set up from the web interface side so it can be done again if necessary.

One thing to think of here is terminology. Right now the workflow is named `CI` and is in file `ci.yaml`. There's one job called `test` but it matrixes out to twelve jobs with wonderful names like `test (2.7, ubuntu-18.04, <=1.10.0,<1.11.0,scipy>=0.11.0,<0.12.0...)`. At some point I can probably fix those names but it's a low priority. There's also a second job called "All tests" that only succeds if all the tests succeed; renaming that in the future requires switching some of the branch protection configuration around. Finally there's the label next to the passing/failing widget in the README; that's currently "CI". All of these are changeable in the future but occasionally have weird little places to chase down, so if better names come immediately to mind I should fix that here before we merge.

## PR Checklist

- [X] Pull request has descriptive title
- [X] Pull request gives overview of changes
- [X] New code has inline comments where necessary
- [X] (N/A) Any new modules, functions or classes have docstrings consistent with SpacePy style
- [X] (N/A) Added an entry to CHANGELOG if fixing a major bug or providing a major new feature
- [X] (N/A) New features and bug fixes should have unit tests
- [X] Relevant issues are linked to (e.g. `See issue #` or `Closes #`)

### CODE REVIEW

**Comment by jtniehof** [comment]
Well, this is cute, looks like the actions don't run on the pull request because they're not merged into master, so you can't actually test CI changes without merging them first. I'll figure this out later.

**Comment by jtniehof** [comment]
So, supposedly it's supposed to find other branches. Maybe. Or PRs. But not from forks. Except now from forks. https://github.community/t/workflow-files-only-picked-up-from-master/16129/16

**Comment by drsteve** [comment]
What do you see needing to happen before this PR comes out of draft status?
If at all possible I'd like to see this be the next PR merged (other than PRs not touching code).  Honestly, since our Travis is defunct I'd be happy to merge almost anything that runs tests...

If there's anything that others can do to help you out here, please shout.

**Comment by jtniehof** [comment]
> What do you see needing to happen before this PR comes out of draft status?

I need the workflow to actually run so that I can then work on getting the actual tests to run. I'm going up and down a rabbit hole trying to actually get GitHub actions to work. It looks like nothing works until you add something to master using the web interface and I'd rather not have a commit on master that's just "add stupid garbage to make GitHub happy."

**Comment by jtniehof** [comment]
Per https://github.community/t/workflow-dispatch-event-not-working/128856/2 it's impossible to trigger a workflow without it having run once on `master`. I think what this means is that I'm going to have to ruin `master` on my fork and then destroy and re-fork after the fact. Then we'll know it works and can hopefully merge this PR "blind" and then hopefully it'll run on the PR forever after.

Alternatively I could do essentially the same thing but just build a no-op workflow first, and open a PR to merge that (similarly mostly blind). That'll get the workflow on master and I can open a second PR to actually do the CI.

**Comment by drsteve** [comment]
Either of those sounds fine, tbh. Adding the workflow and then setting up the CI in a subsequent PR seems easer and cleaner though.

**Comment by jtniehof** [comment]
Okay, I give up for now. I can get this to run nicely as a manual trigger now that it's run once on master. but it will never ever trigger on a PR. I've merged this whole thing into master on my fork and tried to open a PR against that and the tests never run. Need someone else to take a look and see what they can figure.

**Comment by jtniehof** [comment]
Thanks to https://stackoverflow.com/a/65723433/336412 I found the problem...was copying and working from a template not a workflow (and the existence of templates isn't terribly well documented.) Looks like this is running now.

**Comment by jtniehof** [comment]
Two notes: once this is merged I will retrigger all the other pending PRs (close/open).

Also, I will after a week or so submit another PR that changes the time-based build from daily to weekly. I'll synchronize that with the cache expiration so that one will grab fresh versions of all the cached dependencies, and PRs that run later in the week will benefit from the cacheing.

**Comment by jtniehof** [comment]
Looks like there's still an issue here where the individual jobs are reporting status but the overall workflow isn't. [This discussion](https://github.community/t/github-actions-as-status-checks/16666) is vaguely useful but probably already out of date (this stuff has been changing so fast.)

If push comes to shove I can just make a no-op job that depends on all other jobs and we can do the check on that. [This](https://github.com/marketplace/actions/github-checks) might also be useful.

**Comment by jtniehof** [comment]
There are apparently wrinkles to the dependent job approach; [this discussion](https://github.community/t/status-check-for-a-matrix-jobs/127354) (reply 7) seems to have the answer.

**Comment by jtniehof** [comment]
Converting draft to ready-for-review retriggers the CI, BTW. I put that in so we'd have an easy retrigger but it does add another speed hump for people using draft PRs. We can always reconsider it later.

**Comment by drsteve** [comment]
Question: Given that CDF current requires a link with the version number explicitly given, rather than providing a "latest" link that resolves to the latest version, is there any point expiring the cache? (Or at least, could we just do it monthly or something?)
The fixed version isn't going to change, so CDF will only change in our CI when we update the version number we're retrieving.

**Comment by jtniehof** [comment]
> Question: Given that CDF currently requires a link with the version number explicitly given, rather than providing a "latest" link that resolves to the latest version, is there any point expiring the cache? (Or at least, could we just do it monthly or something?)

See #500. I didn't want to waste a lot of effort on cache optimization in the initial setup.

**Comment by drsteve** [comment]
Gotcha. It's nice to be prepared in case SPDF do provide a link that resolves to the latest anyway.
One of my motivations was trying to minimize the runtime of our actions, since there's a limit on the free minutes (2000/month), and I currently can't make that into an approximate number of PRs in my head.
It's probably something we can deal with later if it looks like we're running too much through actions.

**Review by drsteve — APPROVED** [review]

**Comment by jtniehof** [comment]
> Since there's a limit on the free minutes (2000/month), and I currently can't make that into an approximate number of PRs in my head.
[Free for public repositories](https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions) (although there are [concurrency limits](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration)).

One run of our CI is about 20 minutes without the dependencies cached, and about 5 with. (Although I'm spitballing that and we can get a better idea once it's run in cron a few times.) With daily cron jobs and weekly expiration, that's maybe 200/mo. If we added Mac with the same level of rigor, it would be about 2000/mo (10x multiplier) and Windows, 400/mo (2x multiplier.)

We should try to be good citizens (and when we drop 2.7 that will help!) but aren't under the gun.

**Pull request merged**
