### PR TITLE
pycdf support for ISTP-compliant CDFs

### PR DESCRIPTION
**Pull request by jtniehof**
This PR adds a module specifically for CDFs that use ISTP-compliant metadata (as opposed to CDFs in general). There's more to come but these are the first few useful functions.

### CODE REVIEW

**Comment by balarsen** [comment]
This is a great idea and will be useful.

**Comment by jtniehof** [comment]
This should be a little cleaner; moving around some stuff that isn't truly ISTP-specific. @balarsen , do you want to take the initiative to merge if you approve? :)

**Comment by balarsen** [comment]
> This should be a little cleaner; moving around some stuff that isn't truly ISTP-specific. @balarsen , do you want to take the initiative to merge if you approve? :)

Let me download this branch on my mac and play around a bit. Will try for tomorrow,

**Comment by jtniehof** [comment]
@balarsen , @drsteve , thoughts? I'm going to be iterating on this stuff pretty fast for the next few weeks and I think it would be easier if we're able to merge with each small chunk of functionality rather than a bit dump.

**Comment by balarsen** [comment]
@jtniehof I am trying to figure out how to test this on the mac and having issues. Maybe just a documentation thing. I'm in the sphinx docs (spacepy/build/lib/spacepy/Doc/autosummary/spacepy.pycdf.istp.html#module-spacepy.pycdf.istp) and deeper and it is not at all clear with an example on how to actually do anything. 

Can you update the docs with an example? Maybe check an rbsp file or something.

**Comment by jtniehof** [comment]
The "checks" really make the most sense in the context of the istp_checks.py script, although I can certainly do some examples. That's an ISTP compliance check for the CDF file specified on the command line. The focus in on checks that the SPDF checker does NOT do; it's not comprehensive on its own.

This is the first script we've checked in to SpacePy, so I didn't add it to the installer, but I should add documentation--I think we should start a "scripts" section of the docs like the API ref, for now it would just have the one. I can do that and update this PR.

"format" and "fillval" are really pretty specific to "I'm making a CDF and don't want to think about some stuff." What I can do is add a link to the relevant bits of the ISTP spec describing those and then some (mildly stupid) examples.

You can also see the tests as examples, of course.

Again, this doesn't do a huge amount yet, but I want to be ripping on it for awhile.

**Comment by jtniehof** [comment]
Okay, the autodocs failed miserably which is why you weren't seeing much. That should be fixed now and all around better docs plus some examples. Give it a whirl.

**Comment by balarsen** [comment]
@jtniehof , some issues hiding in here somewhere. 

```
24:balarsen@pn1808241 scripts $ python --version
Python 3.7.4

```

This one seems bad...

```
22:balarsen@pn1808241 scripts $ python istp_checks.py ~/Downloads/rbspa_int_ect-hope-sci-L1_20150320_v2.0.0.cdf
Traceback (most recent call last):
  File "istp_checks.py", line 21, in <module>
    main(*sys.argv[1:])
  File "istp_checks.py", line 15, in main
    errs = spacepy.pycdf.istp.FileChecks.all(cdffile)
  File "/Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/istp.py", line 440, in all
    for e in VariableChecks.all(f[v])))
  File "/Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/istp.py", line 111, in all
    errors.extend(f(v))
  File "/Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/istp.py", line 264, in validrange
    if (raw_v.attrs['VALIDMIN'] < minval) or \
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```


this seems suboptimal but ok for an intial cut

```
23:balarsen@pn1808241 scripts $ python istp_checks.py --help
Traceback (most recent call last):
  File "istp_checks.py", line 21, in <module>
    main(*sys.argv[1:])
  File "istp_checks.py", line 14, in main
    with spacepy.pycdf.CDF(f) as cdffile:
  File "/Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/__init__.py", line 1721, in __init__
    self._open(True if readonly is None else readonly)
  File "/Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/__init__.py", line 1902, in _open
    lib.call(const.OPEN_, const.CDF_, self.pathname, ctypes.byref(self._handle))
  File "/Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/__init__.py", line 633, in call
    *(args + (const.NULL_, ))
  File "/Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/__init__.py", line 585, in check_status
    raise CDFError(status)
spacepy.pycdf.CDFError: NO_SUCH_CDF: The specified CDF does not exist.
```

**Comment by jtniehof** [comment]
Oh, that's cute. Thanks. I'm surprised it wasn't caught in the tests. It might be obnoxiously platform or numpy version dependent, so might ask for more.

I can pretty readily argparse the second away.

**Comment by balarsen** [comment]
numpy                         1.17.2
Darwin pn1808241.lanl.gov 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

Happy to test more.

**Comment by jtniehof** [comment]
How on EARTH did you do that? It's not supposed to be possible to have a multi-valued zEntry. I'm working from the public rbspa_rel04_ect-hope-sci-L2_20150320_v6.1.0.cdf and Position_Ion has a 1D three-value VALIDMIN.

It's a PRBEM-MagEphem value but I'm pretty sure I did the filling, not the CDF skeleton for that, or am I misremembering?

**Comment by jtniehof** [comment]
Okay, apparently zEntries (unlike zVars) can have multiple elements for non-string types, and looks like pycdf handles it appropriately. Crazy. ISTP doesn't say you *can't* use one element per dimension of the variable. I'm really surprised CDAWeb hasnt given us trouble for that. Going to need a lot more tests....

**Comment by balarsen** [comment]
Ahh such fun :)

Interesting indeed.

**Comment by jtniehof** [comment]
If it's working, give it to Brian, it won't be for long.

**Comment by jtniehof** [comment]
Wow, that was fun, but it now runs on a HOPE L2 file. (The file fails the checks, but it is actually wrong on some things....)

**Comment by balarsen** [comment]
> If it's working, give it to Brian, it won't be for long.

How do you want to go forward? I am happy to accept this pull request and file bug reports or we can keep sorting here...?

My reputation stands. Another file that crashes the module. 

```
49:balarsen@pn1808241 scripts $ python istp_checks.py /Users/balarsen/Downloads/rbspa_int_ect-hope-tof-L1_20171001_v2.2.0.cdf
/Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/istp.py:262: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if numpy.issubdtype(v.dtype, numpy.float):
Traceback (most recent call last):
  File "istp_checks.py", line 26, in <module>
    main(args.cdffile)
  File "istp_checks.py", line 15, in main
    errs = spacepy.pycdf.istp.FileChecks.all(cdffile)
  File "/Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/istp.py", line 462, in all
    for e in VariableChecks.all(f[v])))
  File "/Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/istp.py", line 111, in all
    errors.extend(f(v))
  File "/Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/istp.py", line 205, in depsize
    actual = dv.shape[int(dv.rv())]
IndexError: tuple index out of range
```

**Comment by balarsen** [comment]
This file just hangs the script in a infinite loop. 

```
59:balarsen@pn1808241 scripts $ python istp_checks.py /Users/balarsen/Downloads/rbspb_rel03_ect-rept-sci-L2_20190624_v5.4.0.cdf
/Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/istp.py:262: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if numpy.issubdtype(v.dtype, numpy.float):
/Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/__init__.py:1196: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif numpy.issubdtype(dtype, numpy.float):
 
```

**Comment by balarsen** [comment]
And an EFW file that kills it

```
60:balarsen@pn1808241 scripts $ python istp_checks.py /Users/balarsen/Downloads/rbspa_l1_vb2_20161210_v02.cdf
Traceback (most recent call last):
  File "istp_checks.py", line 26, in <module>
    main(args.cdffile)
  File "istp_checks.py", line 15, in main
    errs = spacepy.pycdf.istp.FileChecks.all(cdffile)
  File "/Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/istp.py", line 459, in all
    errors.extend(func(f))
  File "/Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/istp.py", line 491, in filename
    if not fname.startswith(f.attrs['Logical_source'][0]):
  File "/Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/__init__.py", line 4279, in __getitem__
    raise IndexError('list index ' + str(key) + ' out of range.')
IndexError: list index 0 out of range.
```

**Comment by jtniehof** [comment]
Let me give those a shot before merge, and anything after that we can go to filing bugs.

**Comment by jtniehof** [comment]
Also I agree that crash is not desirable even for poorly formatted files.

**Comment by jtniehof** [comment]
Confirm the problem with the HOPE and EFW files. REPT file takes a long time but will have to check if it's infinite loop or just slow (numpy.allclose is tragically slow).

**Comment by jtniehof** [comment]
The problem with the slow files was that _so much_ was outside the valid range it was taking a long time to compose the string of 10000 invalid entries. So I limited that to 10 (after that it's a more generic message.)

The other two I fixed.

I also updated the `all()` methods so there's an option to trap errors in subtests, and this is used by the actual script, so there's less chance of the whole thing just blowing up.

And finally for every test I linked the relevant ISTP documentation.

I think this is ready for merge. I also, after this, feel ready to have the script install with the installer (but that will be a future PR), so comments welcome on changing the name, or if `istp_checks.py` is fine.

**Comment by balarsen** [comment]
Thanks for the tenacity here, this is clearly a hard problem to catch all the crazy stuff people do. 

I see one more issue...
`79:balarsen@pn1808241 scripts $ python istp_checks.py /Users/balarsen/Downloads/rbspa_l1_vb2_20161210_v02.cdf`

This goes and seems like it is hung (I will let it go longer in a sec here), I hit ctrl-c, are you catching that? and I get



```
^C/Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/istp.py:299: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if numpy.issubdtype(v.dtype, numpy.float):
No Logical_source in global attrs.
epoch: FIELDNAM attribute Time, UTC does not match var name.
epoch: Test validrange did not complete.
vb2: FIELDNAM attribute EFW AC-Coupled Sensor Voltages, ADC Units does not match var name.
vb2: VALIDMIN element count 3 does not match first data dimension size 6.
vb2: VALIDMAX element count 3 does not match first data dimension size 6.
vb2: Multi dim variable with time_series display type.
vb2_unit: FIELDNAM attribute vb2_labl does not match var name.
vb2_compno: FIELDNAM attribute Sensor coordinate number does not match var name.
ccsds_hdr_packet_length: 13568 values over VALIDMAX 249
hdr_epoch: FIELDNAM attribute Time, UTC does not match var name.

```

**Comment by balarsen** [comment]
Turns out it is just slow. I'll merge this just now. 


```
81:balarsen@pn1808241 scripts $ time python istp_checks.py /Users/balarsen/Downloads/rbspa_l1_vb2_20161210_v02.cdf
/Users/balarsen/anaconda3/envs/python3/lib/python3.7/site-packages/spacepy/pycdf/istp.py:299: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if numpy.issubdtype(v.dtype, numpy.float):
No Logical_source in global attrs.
epoch: FIELDNAM attribute Time, UTC does not match var name.
vb2: FIELDNAM attribute EFW AC-Coupled Sensor Voltages, ADC Units does not match var name.
vb2: VALIDMIN element count 3 does not match first data dimension size 6.
vb2: VALIDMAX element count 3 does not match first data dimension size 6.
vb2: Multi dim variable with time_series display type.
vb2_unit: FIELDNAM attribute vb2_labl does not match var name.
vb2_compno: FIELDNAM attribute Sensor coordinate number does not match var name.
ccsds_hdr_packet_length: 13568 values over VALIDMAX 249
hdr_epoch: FIELDNAM attribute Time, UTC does not match var name.

real	1m37.916s
user	1m37.484s
sys	0m0.779s
```

**Pull request merged**
